# Generated by Django 6.0.5 on 2026-06-03 19:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('paint', 'Paint'), ('electrical', 'Electrical'), ('structural', 'Structural'), ('appliance', 'Appliance'), ('utility', 'Utility'), ('other', 'Other')], default='other', help_text='plumbing / paint / electrical / structural / appliance / utility / other.', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost in Bangladeshi Taka.', max_digits=12)),
                ('date', models.DateField(help_text='When the expense was incurred.')),
                ('source', models.CharField(choices=[('request', 'Request'), ('manual', 'Manual')], default='manual', help_text='request (from a maintenance request) / manual (direct landlord entry).', max_length=8)),
                ('note', models.TextField(blank=True, default='', help_text='Description of the expense.')),
                ('receipt_ref', models.CharField(blank=True, default='', help_text='Receipt image in object storage.', max_length=255)),
                ('unit', models.ForeignKey(help_text='Which unit the expense is for.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='properties.unit')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['unit', 'date'], name='maintenance_unit_id_6604d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('paint', 'Paint'), ('structural', 'Structural'), ('appliance', 'Appliance'), ('utility', 'Utility'), ('other', 'Other')], default='other', help_text='plumbing / electrical / paint / structural / appliance / utility / other.', max_length=16)),
                ('description', models.TextField(help_text="What's wrong.")),
                ('photo_ref', models.CharField(blank=True, default='', help_text='Photo of the problem in object storage.', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', help_text='open / resolved.', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, default=None, help_text='When the issue was fixed.', null=True)),
                ('resolution_cost', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Cost of fixing the issue in Taka. Feeds the auto-expense (T-002).', max_digits=12, null=True)),
                ('resolution_note', models.TextField(blank=True, default='', help_text='Notes on the fix.')),
                ('lease', models.ForeignKey(blank=True, default=None, help_text='The active lease at the time of the request, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='leases.lease')),
                ('unit', models.ForeignKey(help_text='Which unit the request is for.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='properties.unit')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['unit', 'status'], name='maintenance_unit_id_3b432c_idx')],
            },
        ),
    ]
