# Generated by Django 6.0.5 on 2026-06-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='request',
            field=models.OneToOneField(blank=True, default=None, help_text='The maintenance request this expense was auto-created from (source=request). Null for manual expenses. One-to-one so a request can resolve to at most one expense (idempotent resolve).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='maintenance.maintenancerequest'),
        ),
    ]
