# Generated by Django 6.0.5 on 2026-06-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('leases', '0002_seed_lease_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 (inclusive).')),
                ('comment', models.TextField(blank=True, default='', help_text='Free-text comment. May be empty.')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('consented', 'Consented')], default='private', help_text='private (default) / consented. Anything beyond private requires a logged ConsentRecord.', max_length=16)),
                ('revealed_at', models.DateTimeField(blank=True, default=None, help_text='UTC timestamp when this review was revealed to the reviewee (set once the double-blind condition is met or consent is granted).', null=True)),
                ('consent_record', models.ForeignKey(blank=True, default=None, help_text='The logged consent that authorises visibility beyond the reviewer↔reviewee pair. Null for the default private/double-blind case.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='compliance.consentrecord')),
                ('lease', models.ForeignKey(help_text='The lease relationship this review is tied to. A review only exists in the context of one lease — never aggregated across leases.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='leases.lease')),
                ('reviewee', models.ForeignKey(help_text='Who the review is about.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Who wrote the review.', on_delete=django.db.models.deletion.PROTECT, related_name='reviews_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['lease', 'reviewer'], name='reviews_rev_lease_i_aa4d65_idx'), models.Index(fields=['lease', 'reviewee'], name='reviews_rev_lease_i_acf8ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('lease', 'reviewer'), name='uniq_review_per_lease_per_reviewer'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
