# Generated by Django 6.0.5 on 2026-06-03 12:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(help_text='e.g. "Karim Manzil".', max_length=120)),
                ('area', models.CharField(choices=[('uttara', 'Uttara'), ('mirpur', 'Mirpur'), ('mohammadpur', 'Mohammadpur'), ('dhanmondi', 'Dhanmondi'), ('banasree', 'Banasree'), ('gulshan', 'Gulshan'), ('banani', 'Banani'), ('bashundhara', 'Bashundhara'), ('old_dhaka', 'Old Dhaka'), ('other', 'Other')], help_text='Dhaka zone the building sits in.', max_length=16)),
                ('address', models.TextField(help_text='Full address — printed on the DMP form.')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, help_text='Optional map-pin latitude.', max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, default=None, help_text='Optional map-pin longitude.', max_digits=9, null=True)),
                ('owner', models.ForeignKey(help_text='The landlord who owns this building.', on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('label', models.CharField(help_text='e.g. "4B".', max_length=40)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Room'), ('commercial', 'Commercial'), ('garage', 'Garage'), ('other', 'Other')], default='apartment', help_text='apartment / room / commercial / garage / other.', max_length=16)),
                ('rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly rent in Taka.', max_digits=12)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities.')),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('maintenance', 'Maintenance')], default='vacant', help_text='occupied / vacant / maintenance.', max_length=16)),
                ('available_from', models.DateField(blank=True, default=None, help_text='When the unit becomes available.', null=True)),
                ('building', models.ForeignKey(help_text='Parent building; deleting it removes its units.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.building')),
            ],
            options={
                'ordering': ('building', 'label'),
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['owner'], name='properties__owner_i_62475c_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building', 'status'], name='properties__buildin_bf2d73_idx'),
        ),
    ]
