# Generated by Django 6.0.5 on 2026-06-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, default=None, help_text='Optional map-pin latitude.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=9, default=None, help_text='Optional map-pin longitude.', max_digits=12, null=True),
        ),
    ]
