<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-05 08:43
=======
# Generated by Django 6.0.5 on 2026-06-05 08:46
>>>>>>> wave2be/E23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the conversation began.')),
                ('user', models.ForeignKey(help_text='Owner of the conversation. Scoping boundary for all chat access.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat conversation',
                'verbose_name_plural': 'chat conversations',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Who authored the message: user or assistant.', max_length=16)),
                ('content', models.TextField(help_text='The message text.')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'started_at'], name='chatbot_cha_user_id_65937a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatbot_cha_convers_f8ca66_idx'),
        ),
    ]
