# Generated by Django 6.0.5 on 2026-06-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Tenant-selected scope of what to share (e.g. which leases / date range). Selector only — never holds subjective data.')),
                ('factual_stats', models.JSONField(blank=True, default=dict, help_text='FACTUAL stats snapshot computed at share time (on_time_payment_count, total_payments, lease_completed). Counts/booleans only — NO subjective field, ever.')),
                ('expires_at', models.DateTimeField(blank=True, default=None, help_text='When this share stops being readable. Null = no expiry.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, default=None, help_text='When the tenant revoked this share. Null = still live.', null=True)),
                ('consent_record', models.ForeignKey(help_text='The explicit, time-stamped consent logged for THIS share (EPIC-16). PROTECT — consent is append-only and must never be lost.', on_delete=django.db.models.deletion.PROTECT, related_name='history_shares', to='compliance.consentrecord')),
                ('recipient_landlord', models.ForeignKey(help_text='The prospective landlord the tenant chose to share with. A landlord can NEVER initiate this — the tenant always originates.', on_delete=django.db.models.deletion.PROTECT, related_name='received_history_shares', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant who owns and initiated this share. PROTECT — sharing history is tenant-controlled and the record is auditable.', on_delete=django.db.models.deletion.PROTECT, related_name='history_shares', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant'], name='historyshar_tenant__2b7789_idx'), models.Index(fields=['recipient_landlord'], name='historyshar_recipie_3c8688_idx')],
            },
        ),
    ]
