# Generated by Django 6.0.5 on 2026-06-05 09:03

import khatir.historyshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyshare',
            name='token',
            field=models.CharField(default=khatir.historyshare.models.generate_share_token, editable=False, help_text='Opaque, unguessable capability token. The recipient landlord reaches this share ONLY via this token — there is no enumerable id or landlord-initiated lookup path.', max_length=64, unique=True),
        ),
    ]
