# Generated by Django 6.0.5 on 2026-06-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_type', models.CharField(choices=[('all', 'All'), ('role', 'Role'), ('segment', 'Segment'), ('specific', 'Specific')], db_index=True, default='all', help_text='all / role / segment / specific.', max_length=16)),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text="Opaque filter payload; shape varies by audience_type. Empty dict for 'all'.")),
                ('channels', models.JSONField(default=list, help_text="List of Channel wire values, e.g. ['inapp', 'sms'].")),
                ('title_en', models.CharField(help_text='Notification title in English.', max_length=255)),
                ('title_bn', models.CharField(help_text='Notification title in Bangla.', max_length=255)),
                ('body_en', models.TextField(help_text='Notification body in English.')),
                ('body_bn', models.TextField(help_text='Notification body in Bangla.')),
                ('schedule_type', models.CharField(choices=[('now', 'Now'), ('scheduled', 'Scheduled'), ('recurring', 'Recurring')], db_index=True, default='now', help_text='now / scheduled / recurring.', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, default=None, help_text='When to send (only for schedule_type=scheduled/recurring).', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', help_text='draft / scheduled / sending / sent / failed.', max_length=16)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of delivery rows in state >= sent.')),
                ('delivered_count', models.PositiveIntegerField(default=0, help_text='Number of delivery rows in state >= delivered.')),
                ('opened_count', models.PositiveIntegerField(default=0, help_text='Number of delivery rows in state = opened.')),
                ('sender', models.ForeignKey(blank=True, default=None, help_text='Admin user who authored this broadcast. Nullable to allow system-generated notifications.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='admin_portal.adminuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('inapp', 'In-app'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], db_index=True, help_text='inapp / whatsapp / sms / email.', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('failed', 'Failed')], db_index=True, default='queued', help_text='queued / sent / delivered / opened / failed.', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, default=None, help_text='When the channel confirmed delivery.', null=True)),
                ('opened_at', models.DateTimeField(blank=True, default=None, help_text='When the recipient opened / acknowledged the notification.', null=True)),
                ('error', models.TextField(blank=True, default='', help_text='Error message if status = failed.')),
                ('notification', models.ForeignKey(help_text='The parent broadcast.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(help_text='The recipient.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="Stable identifier, e.g. 'rent_reminder'. Unique across templates.", max_length=128, unique=True)),
                ('trigger_event', models.CharField(blank=True, default='', help_text="Internal event name that fires this template (e.g. 'rent.due').", max_length=128)),
                ('channels', models.JSONField(default=list, help_text='List of Channel wire values this template targets.')),
                ('title_en', models.CharField(help_text='Template title in English.', max_length=255)),
                ('title_bn', models.CharField(help_text='Template title in Bangla.', max_length=255)),
                ('body_en', models.TextField(help_text='Template body in English (may contain {variable} placeholders).')),
                ('body_bn', models.TextField(help_text='Template body in Bangla (may contain {variable} placeholders).')),
                ('variables', models.JSONField(blank=True, default=list, help_text="List of placeholder variable names, e.g. ['tenant_name', 'amount'].")),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Disabled templates are not fired by the notification sender.')),
            ],
            options={
                'ordering': ('key',),
                'indexes': [models.Index(fields=['trigger_event'], name='notificatio_trigger_bf38a2_idx'), models.Index(fields=['active'], name='notificatio_active_04ad4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_d92267_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['audience_type'], name='notificatio_audienc_e3df48_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['schedule_type'], name='notificatio_schedul_67e7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'status'], name='notificatio_notific_091a14_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_9111ae_idx'),
        ),
    ]
