# Generated by Django 6.0.5 on 2026-06-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('matched', 'Matched'), ('not_matched', 'Not matched'), ('error', 'Error')], help_text='Boolean-only outcome: matched / not_matched / error.', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', help_text='Opaque vendor transaction id for audit/dispute. NOT the EC data itself — never store raw EC fields here.', max_length=128)),
                ('consent_record', models.ForeignKey(help_text='The consent under which this verification was performed.', on_delete=django.db.models.deletion.PROTECT, related_name='verification_logs', to='compliance.consentrecord')),
                ('requested_by', models.ForeignKey(help_text='The user who initiated the verification attempt.', on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant whose identity was verified.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'verification log',
                'verbose_name_plural': 'verification logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='verificatio_tenant__4da0c1_idx'), models.Index(fields=['result'], name='verificatio_result_84b95a_idx')],
            },
        ),
    ]
