# Generated by Django 6.0.5 on 2026-06-03 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMPFormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.CharField(help_text="The template version used to generate this PDF (e.g. '2024-v1'). Allows distinguishing records across template updates.", max_length=40)),
                ('pdf_ref', models.CharField(help_text='Storage key for the generated PDF in encrypted object storage (EPIC-04 T-003). Never stores the full NID or raw field payload.', max_length=255)),
                ('generated_at', models.DateTimeField(help_text='UTC timestamp when the PDF was generated.')),
                ('generated_by', models.ForeignKey(blank=True, default=None, help_text='The user who triggered PDF generation. SET_NULL — row is kept if the user account is later removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmp_form_records_generated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant whose data populated the form. PROTECT — cannot delete a tenant while DMP form records exist.', on_delete=django.db.models.deletion.PROTECT, related_name='dmp_form_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['tenant'], name='dmpforms_dm_tenant__28043e_idx'), models.Index(fields=['generated_by'], name='dmpforms_dm_generat_886e03_idx'), models.Index(fields=['generated_at'], name='dmpforms_dm_generat_e44433_idx')],
            },
        ),
    ]
