# Generated by Django 6.0.5 on 2026-06-04 08:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount requested in Taka.', max_digits=12)),
                ('period', models.CharField(help_text='The rent month in YYYY-MM format, e.g. "2026-05".', max_length=7)),
                ('link_token', models.CharField(blank=True, default='', help_text="Secret single-purpose token in the tenant's web-link URL (/r/{token}). Populated by the T-002 service, not at create time.", max_length=255, unique=True)),
                ('sent_via', models.CharField(choices=[('inapp', 'In-app'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', help_text='Delivery channel: inapp / whatsapp / sms / email.', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, default=None, help_text='When the request was sent out.', null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('proof_submitted', 'Proof submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='sent', help_text='sent / proof_submitted / verified / rejected.', max_length=16)),
                ('lease', models.ForeignKey(help_text='The lease this request belongs to. PROTECT — financial history is never silently destroyed.', on_delete=django.db.models.deletion.PROTECT, related_name='rent_requests', to='leases.lease')),
                ('rent_schedule', models.ForeignKey(blank=True, default=None, help_text='The scheduled month this answers. Null for a one-off manual request. SET_NULL — clearing a schedule must not delete the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_requests', to='leases.rentschedule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('bkash_txn', 'bKash transaction'), ('nagad_txn', 'Nagad transaction'), ('screenshot', 'Screenshot'), ('photo', 'Photo'), ('note', 'Note')], help_text='bkash_txn / nagad_txn / screenshot / photo / note.', max_length=16)),
                ('value', models.CharField(blank=True, default='', help_text='Transaction id or note text.', max_length=255)),
                ('photo_ref', models.CharField(blank=True, default='', help_text='Pointer to the screenshot/photo in object storage.', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, default=None, help_text='When the tenant submitted this proof.', null=True)),
                ('rent_request', models.ForeignKey(help_text='The request being answered. CASCADE — a proof has no meaning without its request.', on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='rent.rentrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, default=None, help_text='When the landlord confirmed the payment.', null=True)),
                ('receipt_ref', models.CharField(blank=True, default='', help_text='Pointer to the generated receipt PDF in object storage.', max_length=255)),
                ('verified_by', models.ForeignKey(help_text='Who confirmed. PROTECT — keep the audit trail intact.', on_delete=django.db.models.deletion.PROTECT, related_name='payments_verified', to=settings.AUTH_USER_MODEL)),
                ('rent_request', models.ForeignKey(help_text='The settled request. CASCADE — a payment has no meaning without its request.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent.rentrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['link_token'], name='rent_rentre_link_to_f27836_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['lease', 'status'], name='rent_rentre_lease_i_00ec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['rent_request'], name='rent_paymen_rent_re_44760e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rent_request'], name='rent_paymen_rent_re_e30cc0_idx'),
        ),
    ]
