# Generated by Django 6.0.5 on 2026-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrequest',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the most recent reminder was sent (T-008).', null=True),
        ),
        migrations.AddField(
            model_name='rentrequest',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many reminders have been sent for this request (T-008).'),
        ),
    ]
