# Generated by Django 6.0.5 on 2026-06-03 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Stable code: free / per_tenant / bundle_20 / …', max_length=64, unique=True)),
                ('label', models.CharField(help_text='Display name (English).', max_length=120)),
                ('label_bn', models.CharField(help_text='Display name (Bangla).', max_length=120)),
                ('tenant_min', models.IntegerField(default=0, help_text='Minimum tenant count this tier covers.')),
                ('tenant_max', models.IntegerField(blank=True, default=None, help_text='Maximum tenant count; null = unlimited.', null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Monthly price in Taka; null = free.', max_digits=12, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Annual price in Taka; null = free.', max_digits=12, null=True)),
                ('includes_verification', models.BooleanField(default=False, help_text='Does this tier allow NID verification?')),
                ('included_credits', models.IntegerField(default=0, help_text='Bundled NID verification credits.')),
                ('active', models.BooleanField(default=True, help_text='Is this tier currently offered?')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in plan picker (ascending).')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='monthly / annual.', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', help_text='active / past_due / cancelled.', max_length=16)),
                ('start_at', models.DateTimeField(help_text='When this subscription started (UTC).')),
                ('next_billing_at', models.DateTimeField(help_text='When the next billing event is due (UTC).')),
                ('tier', models.ForeignKey(help_text='The plan they are on.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.pricingtier')),
                ('user', models.ForeignKey(help_text='The subscribing landlord.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx')],
            },
        ),
    ]
