# Generated by Django 6.0.5 on 2026-06-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(help_text='Full name.', max_length=120)),
                ('nid_number_enc', models.BinaryField(blank=True, default=None, help_text='The real NID number, encrypted at rest (set in T-002). Never store the plaintext NID in any column.', null=True)),
                ('nid_number_masked', models.CharField(blank=True, default='', help_text='e.g. ****7788 — safe to show and search.', max_length=20)),
                ('dob', models.DateField(blank=True, default=None, help_text='Date of birth (from NID).', null=True)),
                ('address', models.TextField(blank=True, default='', help_text='Permanent address (from NID).')),
                ('photo_ref', models.CharField(blank=True, default='', help_text='Pointer to the encrypted NID image in object storage.', max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('matched', 'Matched'), ('not_matched', 'Not matched'), ('error', 'Error')], default='unverified', help_text='unverified / matched / not_matched / error.', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, default=None, help_text='When EC verification happened.', null=True)),
                ('is_app_user', models.BooleanField(default=False, help_text='Has this tenant installed the app?')),
                ('linked_user', models.ForeignKey(blank=True, default=None, help_text='Their app account, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Family member name.', max_length=120)),
                ('relation', models.CharField(help_text='Relationship to the tenant (e.g. spouse, child).', max_length=40)),
                ('tenant', models.ForeignKey(help_text='The head tenant; deleting them removes their family rows.', on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['nid_number_masked'], name='tenants_ten_nid_num_afa1dd_idx'),
        ),
    ]
