# Generated by Django 6.0.5 on 2026-06-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerOwnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='Lifecycle: pending → active (owner consented) → revoked.', max_length=16)),
                ('permissions_scope', models.JSONField(blank=True, default=list, help_text='List of actions this manager may perform for this owner.')),
                ('consent_record', models.ForeignKey(blank=True, default=None, help_text="The owner's consent event that activated this link, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_owner_links', to='compliance.consentrecord')),
                ('manager', models.ForeignKey(help_text='The managing user (role = manager).', on_delete=django.db.models.deletion.CASCADE, related_name='managed_owner_links', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The property owner being managed (role = landlord).', on_delete=django.db.models.deletion.CASCADE, related_name='manager_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager-owner link',
                'verbose_name_plural': 'manager-owner links',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['manager', 'status'], name='managers_ma_manager_03724f_idx'), models.Index(fields=['owner', 'status'], name='managers_ma_owner_i_fdb3a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('manager', 'owner'), name='uniq_manager_owner_link')],
            },
        ),
    ]
