# Generated by Django 6.0.5 on 2026-06-05 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('sub_manager', 'Sub-manager')], db_index=True, default='staff', help_text='Seat role: staff (scoped worker) or sub_manager (delegate).', max_length=16)),
                ('permissions_scope', models.JSONField(blank=True, default=list, help_text='List of actions this member may perform under the manager.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', help_text='Lifecycle: active → revoked.', max_length=16)),
                ('manager', models.ForeignKey(help_text='The managing user this person works under (role = manager).', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The user occupying this team seat.', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager team member',
                'verbose_name_plural': 'manager team members',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['manager', 'status'], name='managers_ma_manager_d47520_idx'), models.Index(fields=['member', 'status'], name='managers_ma_member__f39624_idx')],
                'constraints': [models.UniqueConstraint(fields=('manager', 'member'), name='uniq_manager_team_member')],
            },
        ),
    ]
