# Generated by Django 6.0.5 on 2026-06-03 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('pdpa_data_collection', 'PDPA data collection'), ('pdpa_nid_verification', 'PDPA NID verification'), ('pdpa_data_sharing', 'PDPA data sharing'), ('marketing', 'Marketing')], help_text='What the user consented to (e.g. pdpa_data_collection).', max_length=32)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp when consent was granted.')),
                ('revoked_at', models.DateTimeField(blank=True, default=None, help_text='UTC timestamp when consent was revoked, if applicable.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, help_text='UTC timestamp when this consent expires (if consent is time-limited).', null=True)),
                ('user', models.ForeignKey(help_text='The user who gave (or withdrew) consent.', on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consent record',
                'verbose_name_plural': 'consent records',
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['user'], name='compliance__user_id_3d48cd_idx'), models.Index(fields=['consent_type'], name='compliance__consent_995ca0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('export', 'Export'), ('delete', 'Delete')], help_text='export or delete.', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='pending / processing / completed / rejected.', max_length=16)),
                ('sla_due', models.DateField(help_text='Date by which the request must be fulfilled (SLA deadline).')),
                ('completed_at', models.DateTimeField(blank=True, default=None, help_text='UTC timestamp when the request was completed or rejected.', null=True)),
                ('handled_by', models.ForeignKey(blank=True, default=None, help_text='The admin staff member who processed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_data_requests', to='admin_portal.adminuser')),
                ('user', models.ForeignKey(help_text='The data subject making the request.', on_delete=django.db.models.deletion.PROTECT, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data request',
                'verbose_name_plural': 'data requests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='compliance__user_id_ae0a97_idx'), models.Index(fields=['status'], name='compliance__status_fdbb9c_idx')],
            },
        ),
    ]
