# Generated by Django 6.0.5 on 2026-06-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Login identity — unique across all admin staff accounts.', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Display name.', max_length=120)),
                ('password_hash', models.CharField(help_text='Django-format hashed password (make_password / check_password). Never store plaintext. Use Argon2 or bcrypt in production.', max_length=255)),
                ('totp_secret_enc', models.CharField(blank=True, default=None, help_text='TOTP base32 secret, encrypted at rest via core.encryption. None until the staff member completes MFA setup.', max_length=512, null=True)),
                ('role', models.CharField(choices=[('super', 'Super'), ('ops', 'Ops'), ('finance', 'Finance'), ('compliance', 'Compliance'), ('support', 'Support')], db_index=True, default='support', help_text='super / ops / finance / compliance / support.', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Optional JSON payload that further restricts what this admin may access (e.g. specific tenant IDs, buildings). Empty dict = no extra restriction.')),
                ('disabled', models.BooleanField(db_index=True, default=False, help_text='Disabled accounts cannot log in to the admin portal.')),
                ('last_login_at', models.DateTimeField(blank=True, default=None, help_text='UTC timestamp of the last successful admin login.', null=True)),
            ],
            options={
                'verbose_name': 'admin user',
                'verbose_name_plural': 'admin users',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['role'], name='admin_porta_role_90accd_idx'), models.Index(fields=['disabled'], name='admin_porta_disable_a79e0b_idx')],
            },
        ),
    ]
