# Generated by Django 6.0.5 on 2026-06-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, help_text="domain.verb action string, e.g. 'admin_user.disable', 'feature_flag.toggle'.", max_length=64)),
                ('entity_type', models.CharField(blank=True, default='', help_text='app_label.model_name of the affected entity (blank if not entity-scoped).', max_length=128)),
                ('entity_id', models.CharField(blank=True, default='', help_text='Primary key of the affected entity, as a string.', max_length=64)),
                ('before_json', models.JSONField(blank=True, default=None, help_text='Snapshot/diff of the affected fields before the change (null for creates).', null=True)),
                ('after_json', models.JSONField(blank=True, default=None, help_text='Snapshot/diff of the affected fields after the change (null for deletes).', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, help_text='Source IP of the request that triggered the action.', null=True)),
                ('reason', models.CharField(blank=True, default='', help_text='Free-text justification supplied by the acting admin.', max_length=255)),
                ('admin_user', models.ForeignKey(blank=True, help_text='The staff account that performed the action (null for system actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='admin_portal.adminuser')),
            ],
            options={
                'verbose_name': 'admin audit entry',
                'verbose_name_plural': 'admin audit entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='admin_porta_admin_u_57b0fa_idx'), models.Index(fields=['action'], name='admin_porta_action_a34bd1_idx')],
            },
        ),
    ]
