"""DMP form domain models — EPIC-05 / ``06_database_schema.md``.

``DMPFormRecord`` persists one row each time a DMP (Dhaka Metropolitan Police)
tenant-registration PDF is generated. It records which tenant the form was for,
which template version was used (so template updates can be tracked and re-runs
distinguished), a pointer to the generated PDF in encrypted object storage, and
the who/when of generation.

Design notes:
- ``pdf_ref`` is a storage key into encrypted object storage (EPIC-04 T-003).
  The full NID number is **never** stored here — see §15 of T-001.
- ``generated_by`` is SET_NULL so staff-account deletions don't destroy audit
  rows; null means "generated by the system / user account no longer exists."
- This is a ledger/generated row, not a user-facing soft-deletable entity, so
  it inherits ``TimeStampedModel`` rather than ``SoftDeleteModel``.
"""

from __future__ import annotations

from django.conf import settings
from django.db import models

from khatir.core.models import TimeStampedModel


class DMPFormRecord(TimeStampedModel):
    """A record of a generated DMP form PDF.

    One row is created each time a PDF is generated. It captures the tenant,
    the template version used, a reference to the stored PDF, and who/when
    triggered the generation.
    """

    tenant = models.ForeignKey(
        "tenants.Tenant",
        on_delete=models.PROTECT,
        related_name="dmp_form_records",
        help_text=(
            "The tenant whose data populated the form. "
            "PROTECT — cannot delete a tenant while DMP form records exist."
        ),
    )
    template_version = models.CharField(
        max_length=40,
        help_text=(
            "The template version used to generate this PDF "
            "(e.g. '2024-v1'). Allows distinguishing records across "
            "template updates."
        ),
    )
    pdf_ref = models.CharField(
        max_length=255,
        help_text=(
            "Storage key for the generated PDF in encrypted object storage "
            "(EPIC-04 T-003). Never stores the full NID or raw field payload."
        ),
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
        related_name="dmp_form_records_generated",
        help_text=(
            "The user who triggered PDF generation. "
            "SET_NULL — row is kept if the user account is later removed."
        ),
    )
    generated_at = models.DateTimeField(
        help_text="UTC timestamp when the PDF was generated.",
    )

    class Meta:
        ordering = ("-generated_at",)
        indexes = [
            models.Index(fields=["tenant"]),
            models.Index(fields=["generated_by"]),
            models.Index(fields=["generated_at"]),
        ]

    def __str__(self) -> str:
        return (
            f"DMPFormRecord #{self.pk} · tenant {self.tenant_id} "
            f"· {self.template_version} · {self.generated_at}"
        )
