# Generated by Django 6.0.5 on 2026-06-05 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', help_text='active / revoked.', max_length=16)),
                ('assigned_by', models.ForeignKey(blank=True, default=None, help_text='The owner/manager who created this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(help_text='The building this caretaker operates the gate for.', on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='properties.building')),
                ('caretaker', models.ForeignKey(help_text='The caretaker User assigned to the building.', on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caretaker assignment',
                'verbose_name_plural': 'caretaker assignments',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['caretaker', 'status'], name='gatekeeper__caretak_a05492_idx'), models.Index(fields=['building', 'status'], name='gatekeeper__buildin_9f255b_idx')],
                'constraints': [models.UniqueConstraint(fields=('caretaker', 'building'), name='uniq_caretaker_building')],
            },
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(help_text='Name the visitor gave at the gate.', max_length=120)),
                ('purpose', models.CharField(blank=True, default='', help_text='Reason for the visit (free text).', max_length=255)),
                ('photo_ref_enc', models.BinaryField(blank=True, default=None, help_text="Encrypted pointer to the visitor's photo in object storage. Set via set_photo_ref(); never a plaintext column.", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', help_text='pending / approved / denied.', max_length=16)),
                ('building', models.ForeignKey(help_text='The building the visitor is entering.', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_entries', to='properties.building')),
                ('logged_by', models.ForeignKey(blank=True, default=None, help_text='The caretaker who logged this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_logged', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, default=None, help_text='The unit being visited, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries', to='properties.unit')),
            ],
            options={
                'verbose_name': 'visitor entry',
                'verbose_name_plural': 'visitor entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['building', 'status'], name='gatekeeper__buildin_4ec06b_idx'), models.Index(fields=['building', 'created_at'], name='gatekeeper__buildin_1cdf13_idx')],
            },
        ),
    ]
