# Generated by Django 6.0.5 on 2026-06-01 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('int', 'Integer'), ('money', 'Money'), ('text', 'Text'), ('bool', 'Boolean')], max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('effective_from', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'system config',
                'verbose_name_plural': 'system config',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=128)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('before', models.JSONField(blank=True, default=None, null=True)),
                ('after', models.JSONField(blank=True, default=None, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['actor', 'created_at'], name='core_audite_actor_i_1ea2f4_idx')],
            },
        ),
    ]
