# Generated by Django 6.0.5 on 2026-06-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_gov_export_config'),
        ('core', '0013_seed_history_flags_config'),
        ('core', '0013_seed_lease_config'),
        ('core', '0013_seed_review_config'),
        ('core', '0014_seed_verification_config'),
    ]

    operations = [
    ]
