# Generated by Django 6.0.5 on 2026-06-03 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('ocr', 'OCR'), ('lease', 'Lease')], help_text='Capability category: chat / voice / ocr / lease.', max_length=8)),
                ('provider_key', models.CharField(help_text="Stable vendor identifier, e.g. 'openai', 'google_vision'.", max_length=64)),
                ('is_primary', models.BooleanField(default=False, help_text='True if this is the primary provider for its category.')),
                ('is_fallback', models.BooleanField(default=False, help_text='True if this provider is used as a fallback.')),
                ('model_name', models.CharField(blank=True, default='', help_text="Model identifier, e.g. 'gpt-4o', 'gemini-2.0-flash'.", max_length=128)),
                ('api_key_enc', models.TextField(blank=True, default='', help_text='Fernet-encrypted API key (from khatir.core.encryption.encrypt). Never store or log the plaintext.')),
                ('endpoint_url', models.URLField(blank=True, default='', help_text='Override endpoint URL; empty means the SDK default.', max_length=255)),
                ('params_json', models.JSONField(blank=True, default=None, help_text='Extra provider-specific parameters (temperature, timeout, etc.).', null=True)),
                ('dpa_reference', models.CharField(blank=True, default='', help_text='Data Processing Agreement reference number. Required before activating a non-BD OCR provider (compliance rule).', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Inactive providers are skipped by the AI routing layer.')),
            ],
            options={
                'verbose_name': 'AI provider',
                'verbose_name_plural': 'AI providers',
                'ordering': ('category', 'provider_key'),
                'indexes': [models.Index(fields=['category', 'is_primary'], name='ai_provider_categor_33ee8d_idx'), models.Index(fields=['category', 'active'], name='ai_provider_categor_21576c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('ocr', 'OCR'), ('lease', 'Lease')], help_text='Denormalised category for direct log queries.', max_length=8)),
                ('request_count', models.PositiveIntegerField(default=1, help_text='Number of API requests aggregated into this log row.')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens consumed (prompt + completion where applicable).')),
                ('cost_usd', models.DecimalField(decimal_places=2, default=0, help_text='Vendor-reported cost in USD for this call.', max_digits=12)),
                ('success', models.BooleanField(default=True, help_text='False if the call failed or returned an error response.')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Round-trip latency in milliseconds.')),
                ('failover_from', models.ForeignKey(blank=True, default=None, help_text='The primary provider that failed, triggering failover to ``provider``. Null when no failover occurred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_logs', to='ai_providers.aiprovider')),
                ('provider', models.ForeignKey(help_text='The provider that handled this call.', on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='ai_providers.aiprovider')),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider', 'created_at'], name='ai_provider_provide_fb3a79_idx'), models.Index(fields=['category', 'created_at'], name='ai_provider_categor_bd86d9_idx'), models.Index(fields=['success'], name='ai_provider_success_02f5c1_idx')],
            },
        ),
    ]
