# Generated by Django 6.0.5 on 2026-06-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="Stable code identifier, e.g. 'nid_ocr_enabled'.", max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable explanation of what this flag controls.')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('role', 'Role'), ('user', 'User')], db_index=True, default='global', help_text='global / role / user.', max_length=8)),
                ('enabled', models.BooleanField(db_index=True, default=False, help_text='Master on/off switch.')),
                ('value_json', models.JSONField(blank=True, default=None, help_text='Optional JSON payload (thresholds, provider config, …). None = no extra config.', null=True)),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='The admin who last changed this flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_flags', to='admin_portal.adminuser')),
            ],
            options={
                'verbose_name': 'feature flag',
                'verbose_name_plural': 'feature flags',
                'ordering': ('key',),
                'indexes': [models.Index(fields=['scope', 'enabled'], name='featureflag_scope_669161_idx')],
            },
        ),
        migrations.CreateModel(
            name='KillSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_key', models.CharField(db_index=True, help_text="Identifies which kill-switch was toggled, e.g. 'payment_gateway'.", max_length=128)),
                ('action', models.CharField(choices=[('disable', 'Disable'), ('enable', 'Enable')], db_index=True, help_text='disable / enable.', max_length=8)),
                ('reason', models.TextField(help_text='Why this switch was thrown. Required for audit compliance.')),
                ('lawyer_reference', models.CharField(blank=True, default='', help_text='Optional legal/ticket reference (e.g. Jira ticket, counsel email).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the event — set once at creation, never changed.')),
                ('admin_user', models.ForeignKey(blank=True, default=None, help_text='The admin who triggered this event; null for automated triggers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='killswitch_events', to='admin_portal.adminuser')),
            ],
            options={
                'verbose_name': 'kill-switch event',
                'verbose_name_plural': 'kill-switch events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['switch_key', 'created_at'], name='featureflag_switch__771a75_idx')],
            },
        ),
    ]
