# Generated by Django 6.0.5 on 2026-06-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featureflags', '0003_seed_ai_lease_flag'),
        ('featureflags', '0003_seed_nid_verification_flag'),
        ('featureflags', '0003_seed_tenant_app_flag'),
    ]

    operations = [
    ]
