# Generated by Django 6.0.5 on 2026-06-01 20:00

import khatir.accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(help_text='Login identity in E.164 format, e.g. +8801712345678.', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('landlord', 'Landlord'), ('manager', 'Manager'), ('tenant', 'Tenant'), ('caretaker', 'Caretaker'), ('admin', 'Admin')], db_index=True, default='landlord', help_text='Decides which app experience this user gets. Set in EPIC-02.', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('language', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], default='bn', help_text='Drives all UI text for this user.', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Disabled accounts cannot log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Can access the Django admin.')),
                ('last_login_at', models.DateTimeField(blank=True, default=None, help_text='For support/security visibility.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', khatir.accounts.managers.UserManager()),
            ],
        ),
    ]
