# Generated by Django 6.0.5 on 2026-06-03 19:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('start_date', models.DateField(help_text='Lease start date.')),
                ('end_date', models.DateField(help_text='Lease end date.')),
                ('rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly rent in Taka.', max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance / security deposit held in Taka.', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('terminated', 'Terminated')], default='draft', help_text='draft / active / ended / terminated.', max_length=16)),
                ('signed_pdf_ref', models.CharField(blank=True, default='', help_text='Pointer to the signed agreement PDF in object storage (P1 e-sign).', max_length=255)),
                ('landlord', models.ForeignKey(help_text='The property owner.', on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_landlord', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Who is renting. PROTECT — cannot delete a tenant while a lease exists.', on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant')),
                ('unit', models.ForeignKey(help_text='Which flat is being rented. PROTECT — cannot delete a unit while a lease exists.', on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='The rent month in YYYY-MM format, e.g. "2026-05".', max_length=7)),
                ('due_day', models.PositiveSmallIntegerField(help_text='Day of month rent is due (e.g. 5 means the 5th of each month).')),
                ('due_date', models.DateField(help_text='Concrete due date for this period (resolved from period + due_day).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due in Taka for this period.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', help_text='pending / requested / paid / overdue.', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, default=None, help_text='When the rent request was sent out (set when status → requested).', null=True)),
                ('lease', models.ForeignKey(help_text='Parent lease. CASCADE — deleting a lease removes its schedule rows.', on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedules', to='leases.lease')),
            ],
            options={
                'ordering': ('lease', 'period'),
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_145517_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit'], name='leases_leas_unit_id_a4eecf_idx'),
        ),
        migrations.AddIndex(
            model_name='rentschedule',
            index=models.Index(fields=['lease', 'status'], name='leases_rent_lease_i_7df254_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentschedule',
            constraint=models.UniqueConstraint(fields=('lease', 'period'), name='leases_rentschedule_unique_lease_period'),
        ),
    ]
