# Generated by Django 6.0.5 on 2026-06-05 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text="The period the export covers, e.g. '2026-05' (YYYY-MM).", max_length=7)),
                ('format_version', models.CharField(help_text="The export format/template version used (e.g. '2024-v1'). Allows distinguishing records across format updates.", max_length=40)),
                ('file_ref', models.CharField(help_text='Storage key for the generated export package in encrypted object storage (EPIC-04 T-003). Never stores raw PII payload.', max_length=255)),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Number of records contained in the export package.')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('submitted', 'Submitted')], default='generated', help_text="Lifecycle status: 'generated' or 'submitted'.", max_length=20)),
                ('landlord', models.ForeignKey(help_text='The landlord who owns this export. PROTECT — cannot delete a landlord while gov-export records exist.', on_delete=django.db.models.deletion.PROTECT, related_name='gov_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['landlord'], name='govexport_g_landlor_8ddf7f_idx'), models.Index(fields=['period'], name='govexport_g_period_ac665c_idx'), models.Index(fields=['status'], name='govexport_g_status_a622bd_idx'), models.Index(fields=['created_at'], name='govexport_g_created_9e58ba_idx')],
            },
        ),
    ]
