# Generated by Django 6.0.5 on 2026-06-05 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_seed_lease_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Ordered clause set as JSON, keyed by clause name (e.g. "rent", "advance", "disclaimer"). Required clauses must be present.')),
                ('pdf_ref', models.CharField(blank=True, default='', help_text='Pointer to the rendered PDF in object storage (set by the PDF render step).', max_length=255)),
                ('model_used', models.CharField(blank=True, default='', help_text='Identifier of the AI model that produced the draft (audit/repro).', max_length=128)),
                ('generated_at', models.DateTimeField(blank=True, default=None, help_text='When the AI draft was produced (set on successful generation).', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', help_text='draft (editable) / final (locked, PDF-ready).', max_length=16)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Landlord who triggered the AI generation. SET_NULL so the document survives user deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lease_documents', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(help_text='Parent lease. CASCADE — a document has no meaning without its lease.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.lease')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['lease', 'status'], name='leasedocs_l_lease_i_28afa8_idx')],
            },
        ),
    ]
