# Generated by Django 6.0.5 on 2026-06-05 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_seed_lease_config'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('warning_type', models.CharField(choices=[('late_rent', 'Late rent'), ('lease_violation', 'Lease violation'), ('noise', 'Noise'), ('other', 'Other')], default='other', help_text='late_rent / lease_violation / noise / other.', max_length=16)),
                ('reason', models.TextField(help_text='Why the warning was issued.')),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='When the warning was issued.')),
                ('notice_ref', models.CharField(blank=True, default='', help_text='Pointer to the generated warning-notice PDF in object storage (T-003). Empty until generated.', max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, default=None, help_text='When the tenant acknowledged the warning, if at all.', null=True)),
                ('landlord', models.ForeignKey(help_text='The landlord who issued the warning. Sole owner of this private record.', on_delete=django.db.models.deletion.PROTECT, related_name='warnings_issued', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(help_text='The lease this warning relates to. PROTECT — a warning is strictly scoped to one lease and is never orphaned.', on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to='leases.lease')),
                ('tenant', models.ForeignKey(help_text='The tenant the warning was issued to.', on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['landlord', 'issued_at'], name='warnings_wa_landlor_c77e66_idx'), models.Index(fields=['lease'], name='warnings_wa_lease_i_5a51ef_idx')],
            },
        ),
    ]
